### ISSUE TITLE
Visual Studio won't compile C version because of DigitDataBase16 function.

### ISSUE THREAD

**Issue by kstencell** [InductiveComputerScience/pbPlots#10]
https://github.com/InductiveComputerScience/pbPlots/blob/3eaec98b885cdbe86e8569751688599a4e54df09/C/pbPlots.c#L3826

I don't understand what this function does and why this string is included but it prevents Visual Studio from compiling.

It causes a C2026 error code "string too big, trailing character truncated."

**Comment by DBJDBJ** [comment]
That happened to me today. So I had to cut that monster string in smaller chunks. That made it work.

Also since that is a compile-time string there is no point making `wcslen` suffer with it. 

Change it to this:

```cpp
wchar_t *DigitDataBase16(size_t *returnArrayLength) {
  static wchar_t monster[] = L" monster string literal here " ;
  *returnArrayLength = (sizeof monster) / (sizeof monster[0]);
  return monster;
}
```
