### ISSUE TITLE
ScatterPlot Series color issue

### ISSUE THREAD

**Issue by StarvedHawk** [InductiveComputerScience/pbPlots#13]
When using color in scatterplot series half the image gets covered by grey coincidentally where the data points start. 
 as shown in the below example, The language used is C
![image](https://user-images.githubusercontent.com/77271343/117803551-cf0c5680-b267-11eb-9586-69c5432221b5.png)

**Comment by martinfjohansen** [comment]
Could you try the latest version of the code?
