### ISSUE TITLE
The "Expression:transposed pointer range" error by using it in C++20

### ISSUE THREAD

**Issue by Nambers** [InductiveComputerScience/pbPlots#15]
My code:
```C++
RGBABitmapImageReference *imageReference = CreateRGBABitmapImageReference();
    vector<double> xs = vector<double>();
    for(int i = 1; i<turn;i++){
        xs.push_back(i);
    }
    vector<double> ys = vector<double>();
    for(int a : s.totalpopulation)
        ys.push_back(a);
    DrawScatterPlot(imageReference, 600, 400, &xs,
                    &ys);

    vector<double> *pngdata = ConvertToPNG(imageReference->image);
    WriteToFile(pngdata, "example1.png");
    DeleteImage(imageReference->image);
```
The ` s.totalpopulation` is in `vector<int>`

The exception:
![image](https://user-images.githubusercontent.com/35139537/119264984-b4e35880-bc17-11eb-9f3d-2bd3ecd6352e.png)

How can i fix this, thanks.

Env:
win10 x64
MSVC
I add the cpp file into my cmake file

**Comment by Nambers** [comment]
oh maybe it is because the dofferent size of xs and ys， i will check it next day， sorry for the unchecked.

**Comment by Nambers** [comment]
After ensuring the size of xs, and ys is same(50), this error still happen, in this line
`DrawScatterPlot(imageReference, 600, 400, &xs, &ys);`

The debugger screen shot:
![image](https://user-images.githubusercontent.com/35139537/119281750-6ced2180-bc69-11eb-9f29-c7e33b907d68.png)

**Comment by martinfjohansen** [comment]
I ran the following code, and it runs well:

`#include "pbPlots.hpp"
#include "supportLib.hpp"
using namespace std;

int main()
{
	vector<int> totalpopulation = vector<int>();
	totalpopulation.push_back(11111);
	totalpopulation.push_back(22222);
	totalpopulation.push_back(33333);
	int turn  = 4;

	RGBABitmapImageReference *imageReference = CreateRGBABitmapImageReference();
    vector<double> xs = vector<double>();
    for(int i = 1; i<turn;i++){
        xs.push_back(i);
    }
    vector<double> ys = vector<double>();
    for(int a : totalpopulation)
        ys.push_back(a);
    DrawScatterPlot(imageReference, 600, 400, &xs,
                    &ys);

    vector<double> *pngdata = ConvertToPNG(imageReference->image);
    WriteToFile(pngdata, "example1.png");
    DeleteImage(imageReference->image);
    return 0;
}`

**Comment by Nambers** [comment]
> I ran the following code, and it runs well. Could you paste your's?
> 
> 
> 
> ```
> 
> #include "pbPlots.hpp"
> 
> #include "supportLib.hpp"
> 
> using namespace std;
> 
> 
> 
> int main()
> 
> {
> 
> 	vector<int> totalpopulation = vector<int>();
> 
> 	totalpopulation.push_back(11111);
> 
> 	totalpopulation.push_back(22222);
> 
> 	totalpopulation.push_back(33333);
> 
> 	int turn  = 4;
> 
> 
> 
> 	RGBABitmapImageReference *imageReference = CreateRGBABitmapImageReference();
> 
>     vector<double> xs = vector<double>();
> 
>     for(int i = 1; i<turn;i++){
> 
>         xs.push_back(i);
> 
>     }
> 
>     vector<double> ys = vector<double>();
> 
>     for(int a : totalpopulation)
> 
>         ys.push_back(a);
> 
>     DrawScatterPlot(imageReference, 600, 400, &xs,
> 
>                     &ys);
> 
> 
> 
>     vector<double> *pngdata = ConvertToPNG(imageReference->image);
> 
>     WriteToFile(pngdata, "example1.png");
> 
>     DeleteImage(imageReference->image);
> 
>     return 0;
> 
> }
> 
> 
> 
> ```

thank for ur help！
i will go check it later
