### ISSUE TITLE
Vector too long

### ISSUE THREAD

**Issue by Jwasik** [InductiveComputerScience/pbPlots#16]
In some unknown conditions PNum variable inside ComputeGridLinePositions() is getting value NaN, which causes exception Vector too long. Its appearing randomly.

**Comment by martinfjohansen** [comment]
Could you give an example where this occurs?

**Comment by Jwasik** [comment]
Found issue. My data was generated randomly and i was performing 3 sec tests. There was a chance that i had no data in 3 secs, so data vector was empty. That leads to lots of unhandled exceptions and NaN values. You should add something like DataVectorEmptyException and everything would be ok.
