### ISSUE TITLE
Substandard C

### ISSUE THREAD

**Issue by DBJDBJ** [InductiveComputerScience/pbPlots#18]
This seems like a useful library. I am a C coder/user. C in here is unfortunately in need of some improvements. Few examples.

What is the point of  double as an argument to malloc, for example
```c
// pbPlots.c line 127
colors = (RGBA**)malloc(sizeof(RGBA) * 8.0);
```
That of course produces a lot of warnings
```
1>~\pbPlots-0.1.7.1\C\pbPlots.c(127,45): warning C4244: 'function': conversion from 'double' to 'size_t', possible loss of data
```
1. standard C is C11. 
2.  these days one does 
```c
// this is VMT not VLA
colors =  malloc( sizeof( RGBA[8] ) );
```
Next. There is even code like this one:
```
// line 151
reference->image->x = (RGBABitmap**)malloc(sizeof(RGBABitmap) * 0.0);
// same as
reference->image->x = NULL ;
// or is it? it depends on the implementation
```
Next. This code is all heap-based. Stack-based code tends to be faster. But that requires refactoring.
There are dozens of unnecessary heap allocations. As an example `CreateRectangle` (line:168) is much faster in this form:
```c
// C struct copy elision is very fast, return by value when making struct instances
Rectangle reateRectangle(double x1, double y1, double x2, double y2){
  Rectangle r = {  .x1 = x1, y1 = y1, .x2 = x2, .y2 = y2 } ;
  return r;
}
```
Also in standard C, there is no need to cast the allocation results.  There are much more opportunities for improvement. 

I assume all is known and this code will be improved.

**Comment by martinfjohansen** [comment]
Hi @DBJDBJ , I do understand that the C code seems a bit odd. The reason it is unusual is that the code is actually written in a subset of C called progsbase. Progsbase is not like other languages. It is a subset of many languages. So, the code you see here is the progsbase subset of C (which is also the progsbase subset of Java, C#, C++ etc). This means the code is automatically available in many other languages and remains readable in all (allthough non-idiomatic).

Regarding your points in the context of the progsbase subset:
* sizeof( RGBA[8] ) -- I did not know about this one. It is a nice improvement :)
* casting: Yes, but then the code does not compile with a C++ compiler, which I think is a nice thing to support. 
* heap-based allocation: Progsbase supports custom allocators, the one generated here is heap-based, but one could do stack-based or even pre-allocated. One selects allocator during code generation.

**Comment by DBJDBJ** [comment]
One way or another: This is bad C code. Even as a subset.  No serious project or team can accept this code.  Neither any modern compiler will without serious and numerous warnings.

Please study: [Jens Gustedt "Modern C"](https://gustedt.gitlabpages.inria.fr/modern-c/)

I wish you all the best
