### ISSUE TITLE
graph a function in C.

### ISSUE THREAD

**Issue by IvantellezS** [InductiveComputerScience/pbPlots#2]
Hello, I am a student and I have a little problem, in my school we need to graph a function and I want to know I can Draw the graph without a line. For example I have this graph and have two lines one of these is the line that I draw and i dont want the other line
![Grafica de la forma y=mx+b](https://user-images.githubusercontent.com/67435666/100125491-74f71080-2e42-11eb-87d2-f19e39a297f0.png)

**Comment by martinfjohansen** [comment]
Hi, could you paste your code here?

**Comment by IvantellezS** [comment]
> Hola, ¿podrías pegar tu código aquí?

#include <stdio.h>
#include "pbPlots.h"
#include "supportLib.h"


int main (){
	
	int r,x1,x2,m,b,y1,y2,rx,ry,i,j=0;
	
	printf("Introduce un rango");
	scanf("%d", &r);
	
	printf("Introduce el valor de m: ");
	scanf("%d", &m);
	printf("Introduce el valor de b: ");
	scanf("%d", &b);
	 
	double x[r];
	double y[r];
	
	x1=-1*(r/2);
	y1=(m*x1)+b;
	
	if(y1<x1){
		y1=x1;
		x1=(y1-b)/m;
	}
	
	x2=(r/2);
	y2=(m*x2)+b;
	if(y2>x2){
		y2=x2;
		x2=(y2-b)/m;
	}

	
	for(i=(-1*(r/2));i<=(r/2);i++){
		y[j]=i;
		x[j]=i;
		j++;
	}

	
RGBABitmapImageReference*imageRef = CreateRGBABitmapImageReference();

DrawScatterPlot(imageRef, 600, 400, x,r, y,r);


double xx = MapXCoordinateAutoSettings(x1, imageRef->image, x,r);
double yy = MapYCoordinateAutoSettings(y1, imageRef->image, y,r);

double xxx = MapXCoordinateAutoSettings(x2, imageRef->image, x,r);
double yyy = MapYCoordinateAutoSettings(y2, imageRef->image, y,r);

DrawLine(imageRef->image, xx, yy, xxx, yyy, 2, GetGray(0.3));

    
	size_t length;
	double *pngData=ConvertToPNG(&length, imageRef->image);
	WriteToFile(pngData,length,"Grafica de la forma y=mx+b.png");
	
	return 0;
}

**Comment by martinfjohansen** [comment]
In your example plot above, which values did you enter for r, m and b?

**Comment by martinfjohansen** [comment]
Try this code: It will shows dots instead of a line.

```
#include <stdio.h>
#include "pbPlots.h"
#include "supportLib.h"

int main (){

    int r,x1,x2,m,b,y1,y2,rx,ry,i,j=0;

    printf("Introduce un rango");
    scanf("%d", &r);

    printf("Introduce el valor de m: ");
    scanf("%d", &m);
    printf("Introduce el valor de b: ");
    scanf("%d", &b);

    double x[r];
    double y[r];

    x1=-1*(r/2);
    y1=(m*x1)+b;

    if(y1<x1){
        y1=x1;
        x1=(y1-b)/m;
    }

    x2=(r/2);
    y2=(m*x2)+b;
    if(y2>x2){
        y2=x2;
        x2=(y2-b)/m;
    }


    for(i=(-1*(r/2));i<=(r/2);i++){
        y[j]=i;
        x[j]=i;
        j++;
    }
    RGBABitmapImageReference*imageRef = CreateRGBABitmapImageReference();

    ScatterPlotSettings *settings;
    settings = GetDefaultScatterPlotSettings();
    settings->width = 600;
    settings->height = 400;

    ScatterPlotSeries *series = GetDefaultScatterPlotSeriesSettings();
    series->xs = x;
    series->xsLength = r;
    series->ys = y;
    series->ysLength = r;
    series->linearInterpolation = false;
    series->pointType = L"dots";
    series->pointTypeLength = wcslen(series->pointType);

    settings->scatterPlotSeries = (ScatterPlotSeries**)malloc(sizeof(ScatterPlotSeries) * 1.0);
    settings->scatterPlotSeriesLength = 1.0;
    settings->scatterPlotSeries[0] = series;

    DrawScatterPlotFromSettings(imageRef, settings);

    double xx = MapXCoordinateAutoSettings(x1, imageRef->image, x,r);
    double yy = MapYCoordinateAutoSettings(y1, imageRef->image, y,r);

    double xxx = MapXCoordinateAutoSettings(x2, imageRef->image, x,r);
    double yyy = MapYCoordinateAutoSettings(y2, imageRef->image, y,r);

    DrawLine(imageRef->image, xx, yy, xxx, yyy, 2, GetGray(0.3));

    size_t length;
    double *pngData=ConvertToPNG(&length, imageRef->image);
    WriteToFile(pngData,length,"Grafica de la forma y=mx+b.png");

    return 0;
}
```

**Comment by IvantellezS** [comment]
> En la gráfica de ejemplo anterior, ¿qué valores ingresó para r, my b?

r=10
m=5
b=15

**Comment by IvantellezS** [comment]
> Prueba este código: mostrará puntos en lugar de una línea.
> 
> ```
> #include <stdio.h>
> #include "pbPlots.h"
> #include "supportLib.h"
> 
> int main (){
> 
>     int r,x1,x2,m,b,y1,y2,rx,ry,i,j=0;
> 
>     printf("Introduce un rango");
>     scanf("%d", &r);
> 
>     printf("Introduce el valor de m: ");
>     scanf("%d", &m);
>     printf("Introduce el valor de b: ");
>     scanf("%d", &b);
> 
>     double x[r];
>     double y[r];
> 
>     x1=-1*(r/2);
>     y1=(m*x1)+b;
> 
>     if(y1<x1){
>         y1=x1;
>         x1=(y1-b)/m;
>     }
> 
>     x2=(r/2);
>     y2=(m*x2)+b;
>     if(y2>x2){
>         y2=x2;
>         x2=(y2-b)/m;
>     }
> 
> 
>     for(i=(-1*(r/2));i<=(r/2);i++){
>         y[j]=i;
>         x[j]=i;
>         j++;
>     }
>     RGBABitmapImageReference*imageRef = CreateRGBABitmapImageReference();
> 
>     ScatterPlotSettings *settings;
>     settings = GetDefaultScatterPlotSettings();
>     settings->width = 600;
>     settings->height = 400;
> 
>     ScatterPlotSeries *series = GetDefaultScatterPlotSeriesSettings();
>     series->xs = x;
>     series->xsLength = r;
>     series->ys = y;
>     series->ysLength = r;
>     series->linearInterpolation = false;
>     series->pointType = L"dots";
>     series->pointTypeLength = wcslen(series->pointType);
> 
>     settings->scatterPlotSeries = (ScatterPlotSeries**)malloc(sizeof(ScatterPlotSeries) * 1.0);
>     settings->scatterPlotSeriesLength = 1.0;
>     settings->scatterPlotSeries[0] = series;
> 
>     DrawScatterPlotFromSettings(imageRef, settings);
> 
>     double xx = MapXCoordinateAutoSettings(x1, imageRef->image, x,r);
>     double yy = MapYCoordinateAutoSettings(y1, imageRef->image, y,r);
> 
>     double xxx = MapXCoordinateAutoSettings(x2, imageRef->image, x,r);
>     double yyy = MapYCoordinateAutoSettings(y2, imageRef->image, y,r);
> 
>     DrawLine(imageRef->image, xx, yy, xxx, yyy, 2, GetGray(0.3));
> 
>     size_t length;
>     double *pngData=ConvertToPNG(&length, imageRef->image);
>     WriteToFile(pngData,length,"Grafica de la forma y=mx+b.png");
> 
>     return 0;
> }
> ```

It was useful for me, thank you very much for your help and your prompt response. :)
