### ISSUE TITLE
Issue with the png file

### ISSUE THREAD

**Issue by ValentinParavy** [InductiveComputerScience/pbPlots#21]
Hello,

My code compiles perfectly but no png file is created. 
Here the method  supposed to plot the curve : 

`void Sol::draw_sol_init(){
    bool sucess;
    StringReference *errorMessage = new StringReference();
    RGBABitmapImageReference *imageRef = CreateRGBABitmapImageReference();
    // m_space, m_sol_init are two vector<double> with the same size
    sucess = DrawScatterPlot(imageRef, 600, 400, &m_space, &m_sol_init, errorMessage);

    if(sucess){
        std::vector<double> *pngdata = ConvertToPNG((*imageRef).image);
        WriteToFile(pngdata, "sol_init.png");
        DeleteImage((*imageRef).image);
        std::cout << "test"  <<std::endl;
    }
    else{
        std::cout << "nsm" << std::endl;
    }

}`

and here my all project
[Mesh.zip](https://github.com/InductiveComputerScience/pbPlots/files/8975713/Mesh.zip)

Thank you in advance for your help.

**Comment by martinfjohansen** [comment]
Hi [ValentinParavy](https://github.com/ValentinParavy)! I downloaded the zip, replaced the four files from the newest pbPlots (pbPlots.cpp, pbPlots.hpp, supportLib.cpp and supportLib.hpp), compiled with g++ and ran it. It worked and produced a working PNG-file:

![sol_init](https://user-images.githubusercontent.com/36367520/188083423-e465283e-fa0e-445f-a171-36ffc32e9a33.png)
