### ISSUE TITLE
Are legends supported?

### ISSUE THREAD

**Issue by LeoBaro** [InductiveComputerScience/pbPlots#22]
Hi guys, I'm trying the c++ version, I was wondering if legends are supported. I can't find any reference in the source code, so I think that they are not supported.

**Comment by martinfjohansen** [comment]
Hi, right, legends are not supported. We do plan adding them.

The best solution right now is to draw a legend using primitives shipped with pbPlots.

 * DrawFilledRectangleWithBorder
 * DrawText

That should be quite straigh forward.
