### ISSUE TITLE
C++ example, FreeAllocations()

### ISSUE THREAD

**Issue by RyanZurrin** [InductiveComputerScience/pbPlots#23]
I am not sure if I should put this here or not, but I am not finding any info when google searching nor can I find the mehtod located anywhere in the files the insturctions have you download when setting up pbPlots so I am curious how to use or where to I find the FreeAllocations() method that is being called in the examples? Thanks for any help with this and my apologizes that it is probably not a real issue just a question I am trying to find an answer to. 

Great work on this library by the way, I find it very useful.

**Comment by martinfjohansen** [comment]
You need to download the latest version of the files in order to get this function. (Select the master branch).

This function is only useful to avoid leaks. If your program is exiting right after having made a plot, you do not need it.

**Comment by RyanZurrin** [comment]
Great! Thanks so much.
