### ISSUE TITLE
X and Y Labels flipped

### ISSUE THREAD

**Issue by RoboticNerd** [InductiveComputerScience/pbPlots#24]
I had to triple check. And it's late so I may still be wrong. 

But it seems the x and y labels are flipped.

Here is a screenshot of a graph with the symptoms:
![Flipped Axis](https://user-images.githubusercontent.com/70571400/201464907-c28fe793-26fd-4257-9cc4-bb243573bcbd.png)

Here is a screenshot of the relevant graphing code snippet:
![Code Snippet](https://user-images.githubusercontent.com/70571400/201464900-fd9c15d8-efef-49c9-b8a1-589718bb23cd.PNG)

And just in case here is code with a single datapoint output:
![Data Point](https://user-images.githubusercontent.com/70571400/201464898-ec6c0f25-359a-4b47-b960-e114973158f7.PNG)
So we know that radii are the larger numbers and are stored in vector radiusses (which I used for graphing x). 

Also, great work, and thanks for making it opensource. I'm glad to see a multi-lingual graphing solution. I also appreciate the autoscaling and nan-ignoring it seems to do.

**Comment by martinfjohansen** [comment]
Hi, sorry for the late reply, I have turned on notifications now.

The issue was resolved in version v0.1.9. Please update to it and the problem should be solved :)

Thanks for the kind words; multi-language libraries are awesome, graphing for everyone for all time!
