### ISSUE TITLE
Works Fine but !!

### ISSUE THREAD

**Issue by Rokhha** [InductiveComputerScience/pbPlots#3]
I can draw graph thanks to your libraries but when i try to import the png into my program it misses the bottom part of it :
![image](https://user-images.githubusercontent.com/56533509/100477153-5d1ac900-309c-11eb-807f-57513aadc5ce.png)
![image](https://user-images.githubusercontent.com/56533509/100477187-77ed3d80-309c-11eb-8fe5-1099fb0d6611.png)

What i find strange its the fact that when i close my app it finish to generate the png :
![image](https://user-images.githubusercontent.com/56533509/100477348-edf1a480-309c-11eb-88b5-14bcab2fa843.png)

**Comment by martinfjohansen** [comment]
Which library are you using to load the PNG?

**Comment by Rokhha** [comment]
I use GTK 2 to load the png

**Comment by martinfjohansen** [comment]
Are you using this function?

```
GtkWidget *image;
image = gtk_image_new_from_file ("myfile.png");
```

If so, did you make sure the file was completely written to the file before loading it?

**Comment by martinfjohansen** [comment]
I tried GTK 2, and it worked. Could you paste your code here?

**Comment by Rokhha** [comment]
`void graph_print(char input_f[], int argc, char* argv[], GtkWidget* widget, gpointer data)
{

    fonction = gtk_label_new(input_f);

    gtk_init(&argc, &argv); 

    gtk_container_remove(GTK_CONTAINER(window), vbox); // Remove previous window

    hbox3 = gtk_hbox_new(TRUE, 10);
    vbox = gtk_vbox_new(FALSE, 30);
    vbox1 = gtk_vbox_new(FALSE, 30);

    gtk_box_pack_start(GTK_BOX(hbox3), fonction, TRUE, FALSE, 10);

    graph_draw();

    image = gtk_image_new_from_file ("src/graph.png");

    gtk_box_pack_start(GTK_BOX(vbox), hbox3, FALSE, FALSE, 5);
    gtk_box_pack_start(GTK_BOX(vbox), image, TRUE, FALSE, 10);
    gtk_container_add(GTK_CONTAINER(window), vbox);

    gtk_widget_show_all(window);

	gtk_main();

    g_signal_connect(window, "destroy", G_CALLBACK(destroy), NULL); 
    

    return 0;
}


void graph_draw()
{

	//récupération des points de la fonction pour les placer sur le graph
	double xs [] = {-10, -1, 0, 1, 10};
	double ys [] = {6, -2, -2, -1, 2};

	//génération des axes 
	ScatterPlotSeries *series = GetDefaultScatterPlotSeriesSettings();
    series->xs = xs;
	series->xsLength = 5;
	series->ys = ys;
	series->ysLength = 5;
	series->linearInterpolation = true;
	series->lineType = L"dashed";
	series->lineTypeLength = wcslen(series->lineType);
	series->lineThickness = 2;
	series->color = GetGray(0.3);

	ScatterPlotSettings *settings = GetDefaultScatterPlotSettings();
    settings->width = 600;
	settings->height = 400;
	settings->autoBoundaries = true;
	settings->autoPadding = true;
  	settings->xLabel = L"X axis";
  	settings->xLabelLength = wcslen(settings->xLabel);
  	settings->yLabel = L"Y axis";
  	settings->yLabelLength = wcslen(settings->yLabel);
	ScatterPlotSeries *s [] = {series};
	settings->scatterPlotSeries = s;
	settings->scatterPlotSeriesLength = 1;

	//Génération d'un .PNG qui contient la représentation graphique de la fonction
	RGBABitmapImageReference *canvasReference = CreateRGBABitmapImageReference();
	DrawScatterPlot(canvasReference, 600, 400, xs, 5, ys, 5);

	size_t length;
	double *pngdata = ConvertToPNG(&length, canvasReference->image);
	WriteToFile(pngdata, length, "src/graph.png");
	DeleteImage(canvasReference->image);

	return 0;
}
`
I put the function i use to generate the plot and the one i use to call it.
Thanks for your replies by the way

**Comment by martinfjohansen** [comment]
I had forgotten to close the file in the WriteFile function. Download the latest version of supportLib.c and things should work nicely.

**Comment by Rokhha** [comment]
Thanks a lot
