### ISSUE TITLE
rectangle conflict with std::rectangle

### ISSUE THREAD

**Issue by Kaaregar** [InductiveComputerScience/pbPlots#4]
I'm using vs2019 and had issue with pbPlots.cpp/.hpp. They are using namespace std and vs used rectangle from wingdi.h instead of local rectangle. 
Solved by changing rectangle on rectangle_pbPlots in all files.

**Comment by martinfjohansen** [comment]
I have now removed "using namespace std" from the header files, and prefixed with std:: instead. This should resolve the problem.
