### ISSUE TITLE
Issue with the plotting

### ISSUE THREAD

**Issue by kapil-iitk** [InductiveComputerScience/pbPlots#7]
The library is working correctly however how to insert a border, grid-on/off and auto marker? Can you please include documentation with respect to C++.

**Comment by martinfjohansen** [comment]
Hi, all progsbase libraries work the same for all languages. Check out the C++ [example2.cpp](https://github.com/InductiveComputerScience/pbPlots/blob/master/Cpp/example2.cpp) and read [the documentation](https://github.com/InductiveComputerScience/pbPlots).

**Comment by martinfjohansen** [comment]
For example, under "Configuration Options" in the documentation you have 

autoBoundaries - boolean - If on, automatically calculate the boundaries of the plot.
xMax, xMin, yMax, yMin - If autoBoundaries are off, these specify the boundaries of the plot.
showGrid - boolean - If on, show the grid.
gridColor - RGBA - Color of the grid, if shown.
