### ISSUE TITLE
Issue with PNG file

### ISSUE THREAD

**Issue by Wiktor204** [InductiveComputerScience/pbPlots#8]
My program is working but do not gave me back PNG file [Wykres f.zip](https://github.com/InductiveComputerScience/pbPlots/files/5939000/Wykres.f.zip)

**Comment by martinfjohansen** [comment]
I tried your code and it works. There is probablty something wrong with the setup of the project. Try to set up the project in Code Blocks from scratch again.

**Comment by Wiktor204** [comment]
Ok thank you. Maybe should I do it as a console aplication or other?

**Comment by martinfjohansen** [comment]
Following a guide, for example this one:

http://wiki.codeblocks.org/index.php/Creating_a_new_project#Adding_a_pre-existing_file

You can read "Adding a pre-existing file" to see how to add the pbPlots files.
